[tool.poetry]
name = "tower-of-babel"
version = "0.0.0"
description = ""
authors = ["Tryton Van Meer <hello@trytonvanmeer.dev>"]

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
